#!/bin/sh

VERSION=$(dpkg-parsechangelog | grep Version | sed 's,^Version: \(.*\)\-.*$,\1,g')
CURRENT_BRANCH=$(svn info | grep URL | cut -d' ' -f 2)

if [ ! -f ../trac_${VERSION}.orig.tar.gz ]; then
    (cd .. ; svn export http://svn.edgewall.com/repos/trac/tags/trac-${VERSION} && \
	tar -czf trac_${VERSION}.orig.tar.gz trac-${VERSION} && \
	echo "Created trac_${VERSION}.orig.tar.gz")
fi

cd ..
rm -rf ../trac-${VERSION}
tar -xzf trac_${VERSION}.orig.tar.gz
svn export --force $CURRENT_BRANCH trac-${VERSION}
cd trac-${VERSION}
dpkg-buildpackage -us -uc -rfakeroot
