// Generated by CoffeeScript 2.3.1
(function() {
  // -*- coding: utf-8 -*-

  // Copyright (C) 2016 Edgewall Software
  // All rights reserved.

  // This software is licensed as described in the file COPYING, which
  // you should have received as part of this distribution. The terms
  // are also available at http://trac.edgewall.org/wiki/TracLicense.

  // This software consists of voluntary contributions made by many
  // individuals. For the exact contribution history, see the revision
  // history and logs, available at http://trac.edgewall.org/log/.

  // Add ''Delete'' ticket action in ticket box and ticket comments.

  // The script is added via the tracopt.ticket.deleter component.

  // It uses the following Trac global variables:
  //  - from add_script_data in tracopt.ticket.deleter: ui
  //    (TODO: generalize this)
  var $, captionedButton, deleteComment, deleteTicket;

  $ = jQuery;

  captionedButton = function(symbol, text) {
    if (ui.use_symbols) {
      return symbol;
    } else {
      return `${symbol} ${text}`;
    }
  };

  deleteTicket = function() {
    return $(`<form action="#" method="get">\n <div class="inlinebuttons">\n  <input type="hidden" name="action" value="delete">\n  <input type="submit"\n         value="${captionedButton('–', _('Delete'))}"\n         title="${_('Delete ticket')}"\n         class="trac-delete">\n </div>\n</form>`);
  };

  deleteComment = function(c) {
    var cdate, cnum;
    // c.id == "trac-change-3-1347886395121000"
    //          0123456789012
    [cnum, cdate] = c.id.substr(12).split('-');
    return $(`<form action="#" method="get">\n <div class="inlinebuttons">\n  <input type="hidden" name="action" value="delete-comment">\n  <input type="hidden" name="cnum" value="${cnum}">\n  <input type="hidden" name="cdate" value="${cdate}">\n  <input type="submit"\n         value="${captionedButton('–', _('Delete'))}"\n         title="${_('Delete comment %(num)s', {
      num: cnum
    })}"\n         class="trac-delete">\n </div>\n</form>`);
  };

  $(document).ready(function() {
    // Insert "Delete" buttons for ticket description and each comment
    $('#ticket .description h3').after(deleteTicket());
    return $('#changelog div.change').each(function() {
      return $('.trac-ticket-buttons', this).prepend(deleteComment(this));
    });
  });

}).call(this);
