#!/bin/sh

VERSION=$(dpkg-parsechangelog | grep Version | sed 's,^Version: \(.*\)\-.*$,\1,g')

if [ ! -f ../trac_${VERSION}.orig.tar.gz ]; then
    (cd .. ; svn export http://svn.edgewall.com/repos/trac/tags/trac-${VERSION} && \
	tar -czf trac_${VERSION}.orig.tar.gz trac-${VERSION} && \
	echo "Created trac_${VERSION}.orig.tar.gz" && \
	rm -rf trac-${VERSION})
fi


