<?xml version="1.0"?>
<!-- RSS generated by Trac v<?cs var:$trac.version ?> on <?cs var:$trac.time ?> -->
<rss version="2.0">
   <?cs set base_url = "http://"+$HTTP.Host ?>
    <channel>
      <?cs if $project.name ?>
        <title><?cs var:$project.name?>: Revisions of <?cs var:$log.path ?></title>
      <?cs else ?>
        <title>Revisions of <?cs var:$log.filename ?></title>
      <?cs /if ?>
      <link><?cs var:$base_url ?><?cs var:$log.href ?></link>
      <description>Trac Log - Revisions of <?cs var:$log.path ?></description>
      <language>en-us</language>
      <generator>Trac v<?cs var:$trac.version ?></generator>
      <?cs each:item = $log.items ?>
       <item>
         <author><?cs var:$item.author ?></author>
         <pubDate><?cs var:$item.gmt ?></pubDate>
         <title><?cs var:$item.rev+': '+$item.shortlog ?></title>	  
         <link><?cs var:$base_url+$item.file_href ?></link>
         <description><?cs var:$item.log.raw ?></description>
         <category>Report</category>
       </item>
      <?cs /each ?>
    </channel>
</rss>
