#
# ChangeLog for <?cs var:log.path ?> 
# 
# Generated by Trac <?cs var:trac.version ?>
# <?cs var:trac.time ?>
#
<?cs each:item = $log.items ?>
<?cs with:changeset = log.changes[item.rev] ?>
<?cs var:changeset.date ?> <?cs
     var:changeset.author ?> [<?cs var:item.rev ?>]
<?cs each:file = $changeset.files ?>
	* <?cs var:file ?>:<?cs 
/each ?>
<?cs var:changeset.message ?>
<?cs /with ?>
<?cs /each ?>
