#!/usr/bin/env python
# -*- coding: iso8859-1 -*-
__author__ = 'Daniel Lundin <daniel@edgewall.com>, Jonas Borgström <jonas@edgewall.com>'
__copyright__ = 'Copyright (c) 2005 Edgewall Software'
__license__ = """
 Copyright (C) 2003, 2004, 2005 Edgewall Software
 Copyright (C) 2003, 2004 Jonas Borgström <jonas@edgewall.com>
 Copyright (C) 2003, 2004 Daniel Lundin <daniel@edgewall.com>
 All rights reserved.

 This software is licensed as described in the file COPYING, which
 you should have received as part of this distribution. The terms
 are also available at http://trac.edgewall.com/license.html.

 This software consists of voluntary contributions made by many
 individuals. For the exact contribution history, see the revision
 history and logs, available at http://projects.edgewall.com/trac/."""

import sys

from trac.scripts.admin import run
sys.exit(run(sys.argv[1:]))
